### ISSUE TITLE
Consider switching to Toml for server

### ISSUE THREAD

**Issue by tomascw** [mysimulation/MySim#13]
FreeSO relies heavily on INI files for majority except the server. The server is uses JSON. FreeSO's server config file is complex and rather difficult to read from a terminal window. I recommend switching to TOML.

TOML is used by Rust and offers similar advantages to JSON but in a cleaner INI-like syntax.
```json
{
  "gameLocation": "C:\\Program Files\\Maxis\\The Sims Online\\TSOClient\\",
  "secret": "38F7E3B816EF9F31BFAB8F4C9716C90D106BD85E9D6913FBB4D833C866F837B0",
  "simNFS": "C:\\Files\\Temp\\fso",

  "database": {
    "connectionString": "server=127.0.0.1;uid=root;pwd=;database=fso2;"
},
```
```toml
gameLocation = "C:\\Program Files\\Maxis\\The Sims Online\\TSOClient\\"
secret = "38F7E3B816EF9F31BFAB8F4C9716C90D106BD85E9D6913FBB4D833C866F837B0"
simNFS = "C:\\Files\\Temp\\fso"
[database]
connectionString = "server=127.0.0.1;uid=root;pwd=;database=fso2;"
```
But FreeSO's config is so complex, we might need to separate the config files, similar to what OpenSim has down.
```json
"services": {
	"tasks":{
		"enabled": true,
		"call_sign": "callisto",
        "binding": "0.0.0.0:35100",
		"internal_host": "127.0.0.1:35",
		"public_host": "127.0.0.1:35",
		"certificate": "auth.east.ea.com.pfx",

		"schedule":[
			{
				"cron":"0 3 * * *", 
				"task":"prune_database", 
				"timeout":3600,
				"parameter":{
				}
			},
			{
				"cron":"0 4 * * *", 
				"task":"bonus", 
				"timeout":3600,
				"shard_id": 1,
				"parameter":{
				}
			}
		],

		"tuning":{
			"bonus":{
				"property_bonus":{
					"per_unit": 10,
					"overrides":{
						"1": 1500,
						"2": 1250,
						"3": 1000
					}
				},
				"visitor_bonus":{
					"per_unit": 8
				}
			}
		}
	},

```
```
[services]
cities = [{"call_sign"=>"ganymede", "id"=>1, "binding"=>"0.0.0.0:33100", "internal_host"=>"127.0.0.1:33", "public_host"=>"127.0.0.1:33", "certificate"=>"auth.east.ea.com.pfx", "maintenance"=>{"cron"=>"0 4 * * *", "timeout"=>3600, "visits_retention_period"=>7, "top100_average_period"=>4}}]
lots = [{"call_sign"=>"europa", "binding"=>"0.0.0.0:34100", "internal_host"=>"127.0.0.1:34", "public_host"=>"127.0.0.1:34", "certificate"=>"auth.east.ea.com.pfx", "max_lots"=>5, "cities"=>[{"id"=>1, "host"=>"127.0.0.1:33100"}]}]
```
This would break computability servers if there was ever a migration. So the JSON parser should be added as a fallback.
